### PR TITLE
Retail data models added.

### PR DESCRIPTION
**Pull request by bcelep**

### CODE REVIEW

**Comment by bcelep** [comment]
This pr includes Retail data models.

**Comment by bcelep** [comment]
> @microsoft-github-policy-service agree company="Microsoft"

@microsoft-github-policy-service agree company="Microsoft"

**Comment by andreabichsel** [comment]
Closed without merging. Moved files to private repo and created a new PR.

**Comment by andreabichsel** [comment]
Closed without merging. Moved files to private repo and created a new PR.

**Pull request closed without merging**
